-- MySQL Script generated by MySQL Workbench
-- Tue Jun 26 11:16:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema homeinventorydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lgrdb` ;

-- -----------------------------------------------------
-- Schema homeinventorydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lgrdb` DEFAULT CHARACTER SET latin1 ;
USE `lgrdb` ;

-- -----------------------------------------------------
-- SAMPLE Table `homeinventorydb`.`users`
-- -----------------------------------------------------
/*CREATE TABLE IF NOT EXISTS `basementfinderdb`.`users` (
  `Username` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(80) NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  `FirstName` VARCHAR(70) NOT NULL,
  `LastName` VARCHAR(70) NOT NULL,
  `Active` BIT NOT NULL,
  `IsAdmin` BIT NOT NULL,
  `resetpasswordUUID` VARCHAR(50),
  `activateaccountUUID` VARCHAR(50),
  `passwordSalt` VARCHAR(150),
  `base64Image` VARCHAR(8000),

  PRIMARY KEY (`Username`))
ENGINE = InnoDB;

*/

/* sample DATA

INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`IsAdmin`,`resetpasswordUUID`,`activateaccountUUID`,`passwordSalt`,`base64Image`) VALUES ('admin','9539662b295b2588cd03e7612c04d350631a1246cbc3c6e41dfbde49aa42cb85','admin@gmail.com','Admin','Admin',1,1,NULL,NULL,"Qw3bxot7gNJzaqomtAJ21GPYHWbCR46ndGlslMuHyt0=",NULL);
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`IsAdmin`,`resetpasswordUUID`,`activateaccountUUID`,`passwordSalt`,`base64Image`) VALUES ('admin2','45757ff31c99052cd9881ba4e671f98b61c7cf3b89e1890e4e9149996bd69f00','admin2@gmail.com','Admin2','Admin2',0,1,NULL,NULL,"UIwrMslybWErXJ7BmqKrKRYNA4oOlmvx3sHMpnEoVXA==",NULL);
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`IsAdmin`,`resetpasswordUUID`,`activateaccountUUID`,`passwordSalt`,`base64Image`) VALUES ('anne','269070e566b2de97f286059522b4da90ef758eec836bf3cf412609bdf3b7756b','anne@gmail.com','Anne','Annerson',1,0,NULL,NULL,"ZyyrxQIxisK4Icq7LXP4YKDaksfYwhwHS9UE/aD4wrU==",NULL);
INSERT INTO `users` (`Username`,`Password`,`Email`,`FirstName`,`LastName`,`Active`,`IsAdmin`,`resetpasswordUUID`,`activateaccountUUID`,`passwordSalt`,`base64Image`) VALUES ('armaan','944e8214f26f6d357141bf6da638dd9205fef961aeae24cc1dd8987c1dac537c','armaansinghkl@gmail.com','Barb','Barber',0,0,NULL,NULL,"NBhynqzJPA19N7wVmIHrp4vSTA8ba6eapjQUIggw/v0==",NULL);
*/